/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Azaelmglw
 */
public class ViewDirecciones extends javax.swing.JPanel {

    /**
     * Creates new form ViewDirecciones
     */
    public ViewDirecciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_id_direccion = new javax.swing.JLabel();
        jlb_calle_direccion = new javax.swing.JLabel();
        jlb_colonia_direccion = new javax.swing.JLabel();
        jlb_numero_direccion = new javax.swing.JLabel();
        jlb_ciudad_direccion = new javax.swing.JLabel();
        jlb_estado_direccion = new javax.swing.JLabel();
        jtf_id_direccion = new javax.swing.JTextField();
        jtf_calle_direccion = new javax.swing.JTextField();
        jtf_colonia_direccion = new javax.swing.JTextField();
        jtf_numero_direccion = new javax.swing.JTextField();
        jtf_ciudad_direccion = new javax.swing.JTextField();
        jtf_estado_direccion = new javax.swing.JTextField();
        jsp_display_controls = new javax.swing.JSeparator();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jlb_id_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_id_direccion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_id_direccion.setText("ID:");

        jlb_calle_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_calle_direccion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_calle_direccion.setText("Calle:");

        jlb_colonia_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_colonia_direccion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_colonia_direccion.setText("Colonia:");

        jlb_numero_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_numero_direccion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_numero_direccion.setText("Número:");

        jlb_ciudad_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_ciudad_direccion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_ciudad_direccion.setText("Ciudad:");

        jlb_estado_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_estado_direccion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_estado_direccion.setText("Estado:");

        jtf_id_direccion.setBackground(new java.awt.Color(102, 102, 102));
        jtf_id_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_id_direccion.setForeground(new java.awt.Color(255, 255, 255));

        jtf_calle_direccion.setBackground(new java.awt.Color(102, 102, 102));
        jtf_calle_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_calle_direccion.setForeground(new java.awt.Color(255, 255, 255));

        jtf_colonia_direccion.setBackground(new java.awt.Color(102, 102, 102));
        jtf_colonia_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_colonia_direccion.setForeground(new java.awt.Color(255, 255, 255));

        jtf_numero_direccion.setBackground(new java.awt.Color(102, 102, 102));
        jtf_numero_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_numero_direccion.setForeground(new java.awt.Color(255, 255, 255));

        jtf_ciudad_direccion.setBackground(new java.awt.Color(102, 102, 102));
        jtf_ciudad_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_ciudad_direccion.setForeground(new java.awt.Color(255, 255, 255));

        jtf_estado_direccion.setBackground(new java.awt.Color(102, 102, 102));
        jtf_estado_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_estado_direccion.setForeground(new java.awt.Color(255, 255, 255));

        jbtn_primero.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_primero.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_primero.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_primero.setText("|<");

        jbtn_anterior.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_anterior.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_anterior.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_anterior.setText("Anterior");

        jbtn_siguiente.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_siguiente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_siguiente.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_siguiente.setText("Siguiente");

        jbtn_ultimo.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_ultimo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_ultimo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_ultimo.setText(">|");

        jbtn_modificar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_modificar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_modificar.setText("Modificar");

        jbtn_agregar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_agregar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_agregar.setText("Agregar");

        jbtn_eliminar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_eliminar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setText("Eliminar");

        jbtn_nuevo.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_nuevo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_nuevo.setText("Nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp_display_controls)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlb_estado_direccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_estado_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlb_ciudad_direccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_ciudad_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlb_id_direccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_id_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlb_calle_direccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_calle_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlb_colonia_direccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_colonia_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlb_numero_direccion)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_numero_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_id_direccion)
                    .addComponent(jtf_id_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_calle_direccion)
                    .addComponent(jtf_calle_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_colonia_direccion)
                    .addComponent(jtf_colonia_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_numero_direccion)
                    .addComponent(jtf_numero_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_ciudad_direccion)
                    .addComponent(jtf_ciudad_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_estado_direccion)
                    .addComponent(jtf_estado_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jsp_display_controls, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_anterior)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_ultimo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_modificar)
                    .addComponent(jbtn_eliminar)
                    .addComponent(jbtn_agregar))
                .addGap(11, 11, 11)
                .addComponent(jbtn_nuevo)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jlb_calle_direccion;
    public javax.swing.JLabel jlb_ciudad_direccion;
    public javax.swing.JLabel jlb_colonia_direccion;
    public javax.swing.JLabel jlb_estado_direccion;
    public javax.swing.JLabel jlb_id_direccion;
    public javax.swing.JLabel jlb_numero_direccion;
    public javax.swing.JSeparator jsp_display_controls;
    public javax.swing.JTextField jtf_calle_direccion;
    public javax.swing.JTextField jtf_ciudad_direccion;
    public javax.swing.JTextField jtf_colonia_direccion;
    public javax.swing.JTextField jtf_estado_direccion;
    public javax.swing.JTextField jtf_id_direccion;
    public javax.swing.JTextField jtf_numero_direccion;
    // End of variables declaration//GEN-END:variables
}
